# Generated by Django 5.1.4 on 2024-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emprestimos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("matricula", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=11)),
                ("status_solicitacao", models.CharField(max_length=50)),
                (
                    "valor_solicitado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "valor_total_ccb",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantidade_parcelas", models.IntegerField()),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_primeiro_vencimento", models.DateField()),
                ("data_assinatura", models.DateField()),
                ("cet_mes", models.DecimalField(decimal_places=4, max_digits=10)),
                ("unidades", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18)),
                ("status_operacao", models.CharField(max_length=50)),
                ("parcelas_pagas", models.IntegerField()),
                ("parcelas_remanescentes", models.IntegerField()),
                ("saldo_devedor", models.DecimalField(decimal_places=3, max_digits=10)),
                ("data_demissao", models.DateField(blank=True, null=True)),
                ("ultimo_pagamento", models.DateField()),
                ("identificador_operacao", models.CharField(max_length=50)),
            ],
        ),
    ]
